### ISSUE TITLE
Remove compliance with ISO standard.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/OK-Pest-Control-Site#1]
![screenshot from 2017-02-06 11-23-41](https://cloud.githubusercontent.com/assets/1911594/22684392/d11b9c54-ed24-11e6-89de-d5b93f3a612c.png)
![screenshot from 2017-02-06 11-24-00](https://cloud.githubusercontent.com/assets/1911594/22684399/d62a49de-ed24-11e6-8d28-ba13e6230a62.png)
Remove text and item stating ISO standard.

**Comment by iliyaM** [comment]
change is done. please add me as a contributors so i can push.

**Comment by MeanEYE** [comment]
Added.

**Comment by iliyaM** [comment]
pushed
